goods_data_dict = {'Milla by trendyol Dress': {'colors': ['Multicoloured'],
                             'currency': 'USD',
                             'details': {'Product Attributes;': [': Crew Neck, Long Sleeve, Midi, Zip, Concealed, Reverse, Flower Print'],
                                         'Product Composition': ['95% Polyester 5% Lycra',
                                                                 'Dress Length: 98 cm',
                                                                 None]},
                             'paths': ['Women', 'Dress', 'Casual Dress'],
                             'photos': ['http://cdn01.modagram.com/milla-by-trendyol-dress/38336/2/5c50bbc1-6157-4d35-a083-4c3fa25260ba.jpg',
                                        'http://cdn01.modagram.com/milla-by-trendyol-dress/38336/2/f2c6f7ee-082a-42f8-a990-922402cc17ee.jpg',
                                        'http://cdn01.modagram.com/milla-by-trendyol-dress/38336/2/c292ed05-b3e7-4a95-b947-6507119531d2.jpg',
                                        'http://cdn01.modagram.com/milla-by-trendyol-dress/38336/2/9a7d4db5-d732-4d53-832a-b59e96dea3b7.jpg'],
                             'price': '32,43',
                             'sizes': ['36', '38', '40'],
                             'url': 'http://en.modagram.com//women/dress-multicoloured/detail/38336/171546'},
 'Modagram All Over Lace Dress': {'colors': ['Black'],
                                  'currency': 'USD',
                                  'details': {'Product Attributes;': [': Boat Neck, Long Sleeve, Midi, Zip, Concealed, Laced, Side',
                                                                      'Lining Type: Full Lining'],
                                              'Product Composition': ['93% Polyamide 7% Elastane',
                                                                      'Lining: 100% Polyester',
                                                                      'Dress Length: 90 cm',
                                                                      None]},
                                  'paths': ['Women', 'Dress', 'Casual Dress'],
                                  'photos': ['http://cdn01.modagram.com/modagram-all-over-lace-dress/38814/2/31ac24cd-c1b1-4f1c-8ed9-bd2bc3ea2d5d.jpg',
                                             'http://cdn01.modagram.com/modagram-all-over-lace-dress/38814/2/194ddafc-10f2-4dba-b2a7-9b3d7ff2e7ba.jpg',
                                             'http://cdn01.modagram.com/modagram-all-over-lace-dress/38814/2/c91daf96-a86d-4343-a1a5-396f7dde179c.jpg'],
                                  'price': '24,32',
                                  'sizes': ['34', '36', '38', '40'],
                                  'url': 'http://en.modagram.com//women/all-over-lace-dress-black/detail/38814/173606'},
 'Modagram Decolette Back Scuba Dress': {'colors': ['Red'],
                                         'currency': 'USD',
                                         'details': {'Product Attributes;': [': Boat Neck, Three Quarter Sleeve, Midi'],
                                                     'Product Composition': ['95% Polyester 5% Elastane',
                                                                             'Dress Length: 85 cm',
                                                                             None]},
                                         'paths': ['Women',
                                                   'Dress',
                                                   'Casual Dress'],
                                         'photos': ['http://cdn01.modagram.com/modagram-decolette-back-scuba-dress/39085/2/25a0aefe-a234-4155-b3d6-d0a7808ace65.jpg',
                                                    'http://cdn01.modagram.com/modagram-decolette-back-scuba-dress/39085/2/c4205b98-aec4-47f1-b1e4-858f3aea5973.jpg',
                                                    'http://cdn01.modagram.com/modagram-decolette-back-scuba-dress/39085/2/573ad25c-c879-4e1b-b09b-8c1f5cc73f31.jpg',
                                                    'http://cdn01.modagram.com/modagram-decolette-back-scuba-dress/39085/2/fb721ab8-da8e-4b66-aa6c-126e2a9490c9.jpg',
                                                    'http://cdn01.modagram.com/modagram-decolette-back-scuba-dress/39085/2/f26738a8-67dc-4948-bb3e-47f125a90fa8.jpg'],
                                         'price': '43,24',
                                         'sizes': ['36', '38', '40'],
                                         'url': 'http://en.modagram.com//women/decolette-back-scuba-dress-red/detail/39085/174649'},
 'Modagram Dress with Net Detail to the Waist and Hem': {'colors': ['Black'],
                                                         'currency': 'USD',
                                                         'details': {'Product Attributes;': [': Boat Neck, Three Quarter Sleeve, Zip, Concealed, Reverse'],
                                                                     'Product Composition': ['95% Polyester 5% Elastane',
                                                                                             None]},
                                                         'paths': ['Women',
                                                                   'Dress',
                                                                   'Casual Dress'],
                                                         'photos': ['http://cdn01.modagram.com/modagram-dress-with-net-detail-to-the-waist-and-hem/37795/2/fef83a7b-6e6e-4c71-a2bf-d64339547873.jpg',
                                                                    'http://cdn01.modagram.com/modagram-dress-with-net-detail-to-the-waist-and-hem/37795/2/7eff0b84-6074-4199-853b-d1582bc78908.jpg',
                                                                    'http://cdn01.modagram.com/modagram-dress-with-net-detail-to-the-waist-and-hem/37795/2/c14f5c54-c936-45b0-b1eb-c05c7e20a701.jpg',
                                                                    'http://cdn01.modagram.com/modagram-dress-with-net-detail-to-the-waist-and-hem/37795/2/ca1d1e71-5090-42a9-8233-1ca237086e1b.jpg'],
                                                         'price': '21,62',
                                                         'sizes': ['36',
                                                                   '38',
                                                                   '40'],
                                                         'url': 'http://en.modagram.com//women/dress-with-net-detail-to-the-waist-and-hem-black/detail/37795/168566'},
 'Modagram Femina One Shoulder Evening Dress': {'colors': ['Red',
                                                           'Black',
                                                           'Blue'],
                                                'currency': 'USD',
                                                'details': {'Product Attributes;': [': One Shoulder, Sleeveless, Maxi, Necklace is not Included'],
                                                            'Product Composition': ['95% Polyester 5% Elastane',
                                                                                    'Dress Length: 160 cm',
                                                                                    'Model Wears: 36',
                                                                                    None]},
                                                'paths': ['Women',
                                                          'Dress',
                                                          'Evening Dress'],
                                                'photos': ['http://cdn01.modagram.com/modagram-femina-one-shoulder-evening-dress/35471/2/f73add3d-4cb5-4ae0-8371-34697c5e3a29.jpg',
                                                           'http://cdn01.modagram.com/modagram-femina-one-shoulder-evening-dress/35471/2/1d7a6fd2-aa45-451d-9e50-58146624b091.jpg',
                                                           'http://cdn01.modagram.com/modagram-femina-one-shoulder-evening-dress/35471/2/916294fe-7844-42ca-83a4-31d6e54bf57a.jpg'],
                                                'price': '43,24',
                                                'sizes': ['36', '38', '40'],
                                                'url': 'http://en.modagram.com//women/femina-one-shoulder-evening-dress-black/detail/35471/174471'},
 'Modagram Laced Shoulders Scater Dress': {'colors': ['Red'],
                                           'currency': 'USD',
                                           'details': {'Product Attributes;': [': Boat Neck, Three Quarter Sleeve, Midi, Zip, Concealed, Laced, Reverse'],
                                                       'Product Composition': ['92% Polyester 8% Elastane',
                                                                               'Dress Length: 87 cm',
                                                                               'Skirt Length: 50 cm',
                                                                               None]},
                                           'paths': ['Women',
                                                     'Dress',
                                                     'Casual Dress'],
                                           'photos': ['http://cdn01.modagram.com/modagram-laced-shoulders-scater-dress/37782/2/f0e32485-8f97-436c-83e6-e031c4d5ae4d.jpg',
                                                      'http://cdn01.modagram.com/modagram-laced-shoulders-scater-dress/37782/2/69127ef8-b059-4e25-ae15-b8b1f17d4063.jpg',
                                                      'http://cdn01.modagram.com/modagram-laced-shoulders-scater-dress/37782/2/0a848f74-01a6-402e-ab25-5d506c1c46f0.jpg',
                                                      'http://cdn01.modagram.com/modagram-laced-shoulders-scater-dress/37782/2/2af36b07-5c4d-4edc-bf4a-608bf1a08466.jpg'],
                                           'price': '37,83',
                                           'sizes': ['36', '38', '40'],
                                           'url': 'http://en.modagram.com//women/laced-shoulders-scater-dress-red/detail/37782/168513'},
 'Modagram Leather Detailed Dress': {'colors': ['Black'],
                                     'currency': 'USD',
                                     'details': {'Product Attributes;': [': V Neck, Sleeveless, Midi, Zip, Visible, Reverse'],
                                                 'Product Composition': ['95% Polyester 5% Elastane',
                                                                         None]},
                                     'paths': ['Women',
                                               'Dress',
                                               'Casual Dress'],
                                     'photos': ['http://cdn01.modagram.com/modagram-leather-detailed-dress/39089/2/a1ef5c0f-27cb-45a4-8d5b-7b5fd121ed72.jpg',
                                                'http://cdn01.modagram.com/modagram-leather-detailed-dress/39089/2/b9b63d66-610a-498d-8234-d0bd246c4740.jpg',
                                                'http://cdn01.modagram.com/modagram-leather-detailed-dress/39089/2/2f630c1f-1667-47ff-8476-8e30e3e67b93.jpg',
                                                'http://cdn01.modagram.com/modagram-leather-detailed-dress/39089/2/73c7b88a-1b42-424e-8d20-3daba2ea1a92.jpg'],
                                     'price': '37,83',
                                     'sizes': ['36', '38', '40'],
                                     'url': 'http://en.modagram.com//women/leather-detailed-dress-black/detail/39089/174658'},
 'Modagram Marion Cahined Collar Dress': {'colors': ['Black'],
                                          'currency': 'USD',
                                          'details': {'Product Attributes;': [': Boat Neck, Sleeveless, Midi, Button to the Neck'],
                                                      'Product Composition': ['95% Polyester 5% Elastane',
                                                                              'Dress Length: 92 cm',
                                                                              None]},
                                          'paths': ['Women',
                                                    'Dress',
                                                    'Casual Dress'],
                                          'photos': ['http://cdn01.modagram.com/modagram-marion-cahined-collar-dress/39681/2/90d91b6a-1982-434f-9b90-c9e3dab1eb8c.jpg',
                                                     'http://cdn01.modagram.com/modagram-marion-cahined-collar-dress/39681/2/2553342f-e60b-4c28-abf0-ac0ff8106e40.jpg',
                                                     'http://cdn01.modagram.com/modagram-marion-cahined-collar-dress/39681/2/5e8cf35c-2d71-4231-9492-a74851910304.jpg',
                                                     'http://cdn01.modagram.com/modagram-marion-cahined-collar-dress/39681/2/c43bb2bc-5a32-4576-a649-7d0c22496e29.jpg'],
                                          'price': '37,83',
                                          'sizes': ['36', '38', '40'],
                                          'url': 'http://en.modagram.com//women/marion-cahined-collar-dress-black/detail/39681/176803'},
 'Modagram Open Back Velvet Dress': {'colors': ['Claret', 'Navy'],
                                     'currency': 'USD',
                                     'details': {'Product Attributes;': [': Boat Neck, Long Sleeve'],
                                                 'Product Composition': ['95% Polyester 5% Elastane',
                                                                         'Dress Length: 88 cm',
                                                                         None]},
                                     'paths': ['Women',
                                               'Dress',
                                               'Casual Dress'],
                                     'photos': ['http://cdn01.modagram.com/modagram-open-back-velvet-dress/37803/2/967ca130-f90e-45ed-bd16-9a63265e2393.jpg',
                                                'http://cdn01.modagram.com/modagram-open-back-velvet-dress/37803/2/4a529f5b-9d02-4232-adae-f9c0a59ad60c.jpg',
                                                'http://cdn01.modagram.com/modagram-open-back-velvet-dress/37803/2/ca31ec59-2d74-410d-993d-1a477645a67e.jpg',
                                                'http://cdn01.modagram.com/modagram-open-back-velvet-dress/37803/2/fff6d028-a321-41b7-bce3-24cd8ce624f0.jpg',
                                                'http://cdn01.modagram.com/modagram-open-back-velvet-dress/37803/2/d35f34d1-9d02-4c4c-882d-9638024c46d3.jpg'],
                                     'price': '21,62',
                                     'sizes': ['36', '38', '40'],
                                     'url': 'http://en.modagram.com//women/open-back-velvet-dress-navy/detail/37803/168599'},
 'Modagram Paola Sequin Embellished Dress': {'colors': ['Black',
                                                        'Midnight Blue'],
                                             'currency': 'USD',
                                             'details': {'Product Attributes;': [': Boat Neck, Sleeveless, Sequin Embellished'],
                                                         'Product Composition': ['83% Polyester 14% Viscose 3% Elastane',
                                                                                 'Dress Length: 88 cm',
                                                                                 None]},
                                             'paths': ['Women',
                                                       'Dress',
                                                       'Casual Dress'],
                                             'photos': ['http://cdn01.modagram.com/modagram-paola-sequin-embellished-dress/38541/2/829a34f3-d4a3-4169-ac3c-c2e02c87705e.jpg',
                                                        'http://cdn01.modagram.com/modagram-paola-sequin-embellished-dress/38541/2/05d51d40-6d62-4eae-b6df-2b4444f7b603.jpg',
                                                        'http://cdn01.modagram.com/modagram-paola-sequin-embellished-dress/38541/2/757b035a-3323-4c70-861c-3a61f4453c4f.jpg',
                                                        'http://cdn01.modagram.com/modagram-paola-sequin-embellished-dress/38541/2/e7f169df-4648-483e-aa30-a0432e676b59.jpg'],
                                             'price': '21,62',
                                             'sizes': ['34',
                                                       '36',
                                                       '38',
                                                       '40'],
                                             'url': 'http://en.modagram.com//women/paola-sequin-embellished-dress-black/detail/38541/172563'},
 'Modagram Tony Skater Dress with Laced Collar': {'colors': ['Claret',
                                                             'Black',
                                                             'Red'],
                                                  'currency': 'USD',
                                                  'details': {'Product Attributes;': [': Boat Neck, Long Sleeve, Midi, Zip, Concealed, Laced, Side'],
                                                              'Product Composition': ['95% Polyester 5% Elastane',
                                                                                      'Dress Length: 90 cm',
                                                                                      'Skirt Length: 52 cm',
                                                                                      'Model Wears: 36',
                                                                                      None]},
                                                  'paths': ['Women',
                                                            'Dress',
                                                            'Casual Dress'],
                                                  'photos': ['http://cdn01.modagram.com/modagram-tony-skater-dress-with-laced-collar/34767/2/56b7b7d7-614b-4b23-a3f7-15ef1de7d28f.jpg',
                                                             'http://cdn01.modagram.com/modagram-tony-skater-dress-with-laced-collar/34767/2/764b268e-016d-41a1-9e52-8c798b04acd3.jpg',
                                                             'http://cdn01.modagram.com/modagram-tony-skater-dress-with-laced-collar/34767/2/378e392f-3d52-4b2d-9c0c-35dc1257b88e.jpg',
                                                             'http://cdn01.modagram.com/modagram-tony-skater-dress-with-laced-collar/34767/2/74f9a593-9ab2-47db-92f6-95056380ef7a.jpg'],
                                                  'price': '32,43',
                                                  'sizes': ['36', '38', '40'],
                                                  'url': 'http://en.modagram.com//women/tony-skater-dress-with-laced-collar-red/detail/34767/176043'},
 'Only Dress': {'colors': ['Gray', 'Black'],
                'currency': 'USD',
                'details': {'Product Composition': ['50% Polyester 50% Viscose',
                                                    'Dress Length: 85 cm',
                                                    'Model Wears: 36']},
                'paths': ['Women', 'Dress', 'Casual Dress'],
                'photos': ['http://cdn01.modagram.com/only-dress/31947/2/49af1cb3-d141-4c29-9796-4ecb2a66b9e6.jpg',
                           'http://cdn01.modagram.com/only-dress/31947/2/93a66dec-4b97-4d50-86c1-ad7d5cbed21b.jpg',
                           'http://cdn01.modagram.com/only-dress/31947/2/f0a3ad69-f899-4fc6-952f-91a627821b17.jpg',
                           'http://cdn01.modagram.com/only-dress/31947/2/cffa8168-f015-49c8-a1ee-153a1649a730.jpg'],
                'price': '18,9',
                'sizes': ['34', '36', '38', '40'],
                'url': 'http://en.modagram.com//women/dress-gray/detail/31947/137921'},
 'Rare London Mini Dress': {'colors': ['Black', 'Gold'],
                            'currency': 'USD',
                            'details': {'Model Measurements;': ['Height: 1.76cm',
                                                                'Bust: 82cm \xa0Waist: 60cm \xa0Hip: 90cm',
                                                                'Size: S/36/1\xa0\xa0 Denim Size: 27-32',
                                                                None,
                                                                None,
                                                                None],
                                        'Product Attributes;': [': Sleeveless, Mini, Zip, Visible, Sequin Embellished, Reverse',
                                                                'Lining Type: Full Lining']},
                            'paths': ['Dress', 'Evening Dress'],
                            'photos': ['http://cdn01.modagram.com/rare-london-mini-dress/8158/2/8614f735-59c4-4a85-abd1-bd9e43e06e3b.jpg',
                                       'http://cdn01.modagram.com/rare-london-mini-dress/8158/2/2f3b5265-021f-4efc-854e-ab4ea8df7fe4.jpg',
                                       'http://cdn01.modagram.com/rare-london-mini-dress/8158/2/ce38efd8-2a55-4e32-b07e-74debfa59b4d.jpg',
                                       'http://cdn01.modagram.com/rare-london-mini-dress/8158/2/79d79676-bd1f-42b4-b840-a1a4ff392f19.jpg'],
                            'price': '63,53',
                            'sizes': ['34', '36', '38', '40'],
                            'url': 'http://en.modagram.com//women/mini-dress-gold/detail/8158/156546'},
 'Rare London Strapless Peplum Dress': {'colors': ['Gold', 'Gold'],
                                        'currency': 'USD',
                                        'details': {'Model Measurements;': ['Height: 1.76cm',
                                                                            'Bust: 82cm \xa0Waist: 60cm \xa0Hip: 90cm',
                                                                            'Size: S/36/1\xa0\xa0 Denim Size: 27-32',
                                                                            None,
                                                                            None],
                                                    'Product Attributes;': [': Strapped, Mini, Zip, Visible, Reverse',
                                                                            'Lining Type: Full Lining']},
                                        'paths': ['Women',
                                                  'Dress',
                                                  'Evening Dress'],
                                        'photos': ['http://cdn01.modagram.com/rare-london-strapless-peplum-dress/8162/2/119f0c67-7985-498c-97ac-f87da6cb301c.jpg',
                                                   'http://cdn01.modagram.com/rare-london-strapless-peplum-dress/8162/2/142fc30e-70bb-4f34-8a42-29db24b47c6c.jpg',
                                                   'http://cdn01.modagram.com/rare-london-strapless-peplum-dress/8162/2/76b4b4c6-3c8b-4603-baff-64c0e242fa08.jpg',
                                                   'http://cdn01.modagram.com/rare-london-strapless-peplum-dress/8162/2/e9d7e34b-f26a-4136-ae5f-3d6938be9d7c.jpg'],
                                        'price': '100,08',
                                        'sizes': ['34', '36', '38', '40'],
                                        'url': 'http://en.modagram.com//women/strapless-peplum-dress-gold/detail/8162/156537'},
 'Vero Moda Fabia Dress': {'colors': ['Navy', 'Ecru'],
                           'currency': 'USD',
                           'details': {'Product Attributes;': [': V Neck, Sleeveless, Midi, Unprinted, Two-Pocket-Style',
                                                               'Lining Type: Full Lining'],
                                       'Product Composition': ['90% Polyester 10% Elastane',
                                                               None,
                                                               None,
                                                               None]},
                           'paths': ['Women', 'Dress', 'Casual Dress'],
                           'photos': ['http://cdn01.modagram.com/vero-moda-fabia-dress/32523/2/01e75172-5818-4b41-92f7-9e08fac2b21b.jpg',
                                      'http://cdn01.modagram.com/vero-moda-fabia-dress/32523/2/945c393e-0a32-4baf-ac37-bbbeeffb40cd.jpg',
                                      'http://cdn01.modagram.com/vero-moda-fabia-dress/32523/2/4f7706ac-335e-4e8f-b541-814a77a46e88.jpg',
                                      'http://cdn01.modagram.com/vero-moda-fabia-dress/32523/2/54d9bc77-1cca-4f6e-9b39-69118e97a7d0.jpg'],
                           'price': '24,3',
                           'sizes': ['XS', 'S', 'M', 'L', 'XL'],
                           'url': 'http://en.modagram.com//women/fabia-dress-ecru/detail/32523/141283'},
 'Vero Moda Maya Dress': {'colors': ['Black', 'Ecru'],
                          'currency': 'USD',
                          'details': {'Product Attributes;': [': Boat Neck, Short Sleeve, Midi, Zip, Concealed'],
                                      'Product Composition': ['64% Polyester 34% Viscose 2% Elastane',
                                                              'Concealed Zip Fastening to the Reverse',
                                                              'Dress Length: 84 cm',
                                                              'Model Wears: S']},
                          'paths': ['Women', 'Dress', 'Casual Dress'],
                          'photos': ['http://cdn01.modagram.com/vero-moda-maya-dress/32304/2/01186015-6fd9-434d-a507-fcba86396e7e.jpg',
                                     'http://cdn01.modagram.com/vero-moda-maya-dress/32304/2/2aa293dc-771e-4cc4-a873-ba7abb8db971.jpg',
                                     'http://cdn01.modagram.com/vero-moda-maya-dress/32304/2/e9dd174b-abb0-4107-947c-72c86af7fedc.jpg',
                                     'http://cdn01.modagram.com/vero-moda-maya-dress/32304/2/21ba4f6f-b676-4d3a-a138-3e666f4f7c50.jpg'],
                          'price': '24,3',
                          'sizes': ['XS', 'S', 'M', 'L', 'XL'],
                          'url': 'http://en.modagram.com//women/maya-dress-ecru/detail/32304/140000'},
 'Vero Moda Neje Dress': {'colors': ['White', 'Blue'],
                          'currency': 'USD',
                          'details': {'Product Attributes;': [': Boat Neck, Sleeveless, Midi, Button to the Neck',
                                                              'Lining Type: Full Lining'],
                                      'Product Composition': ['100% Polyester',
                                                              'Same Color Lining',
                                                              'One Button Closure to the Neck',
                                                              None,
                                                              None,
                                                              None,
                                                              None,
                                                              None]},
                          'paths': ['Women', 'Dress', 'Casual Dress'],
                          'photos': ['http://cdn01.modagram.com/vero-moda-neje-dress/32862/2/b25f97d4-ee70-453b-9e87-2323c6391d4a.jpg',
                                     'http://cdn01.modagram.com/vero-moda-neje-dress/32862/2/372330bc-5efe-43bc-af79-a0e8c3519bb3.jpg',
                                     'http://cdn01.modagram.com/vero-moda-neje-dress/32862/2/d2122882-30e6-4fdd-853f-6bd03ca37df5.jpg',
                                     'http://cdn01.modagram.com/vero-moda-neje-dress/32862/2/2d8d9028-7e9a-4867-936f-ca10b8a61f92.jpg'],
                          'price': '28,36',
                          'sizes': ['XS', 'S', 'M', 'L', 'XL'],
                          'url': 'http://en.modagram.com//women/neje-dress-blue/detail/32862/143506'},
 'Vero Moda Orange Dress': {'colors': ['Blue', 'Orange'],
                            'currency': 'USD',
                            'details': {'Product Attributes;': [': Collarless, Midi, Zip, Concealed'],
                                        'Product Composition': ['64% Polyester 34% Viscose 2% Elastane',
                                                                'Concealed Zip Fastening to the Reverse',
                                                                'Dress Length: 85 cm',
                                                                'Model Wears: S']},
                            'paths': ['Women', 'Dress', 'Casual Dress'],
                            'photos': ['http://cdn01.modagram.com/vero-moda-orange-dress/32303/2/57342d12-1cb6-4655-8613-1d287e3994b1.jpg',
                                       'http://cdn01.modagram.com/vero-moda-orange-dress/32303/2/6318c956-5d09-4be1-ba06-fe3a40d34c45.jpg',
                                       'http://cdn01.modagram.com/vero-moda-orange-dress/32303/2/aef3dd70-e6d4-4342-b38d-cb41d5df2eec.jpg',
                                       'http://cdn01.modagram.com/vero-moda-orange-dress/32303/2/e7d7dba6-f4a3-47b1-8e22-03ddbc941b43.jpg'],
                            'price': '24,3',
                            'sizes': ['XS', 'S', 'M', 'L', 'XL'],
                            'url': 'http://en.modagram.com//women/orange-dress-blue/detail/32303/139993'},
 'Y.A.S. Kym Organza Detailed Dress': {'colors': ['Black'],
                                       'currency': 'USD',
                                       'details': {'Product Attributes;': [': Crew Neck, Short Sleeve, Mini, Visible, Reverse',
                                                                           'Lining Type: Full Lining'],
                                                   'Product Composition': ['100% Polyester',
                                                                           None,
                                                                           None,
                                                                           None]},
                                       'paths': ['Women',
                                                 'Dress',
                                                 'Casual Dress'],
                                       'photos': ['http://cdn01.modagram.com/y-a-s-kym-organza-detailed-dress/34162/2/b9d5375b-b5fa-4bfd-ab58-923643ab2f44.jpg',
                                                  'http://cdn01.modagram.com/y-a-s-kym-organza-detailed-dress/34162/2/7435d792-231e-4e82-8f77-134199bb3bb9.jpg',
                                                  'http://cdn01.modagram.com/y-a-s-kym-organza-detailed-dress/34162/2/2d76a820-b090-4442-a822-89873711e058.jpg',
                                                  'http://cdn01.modagram.com/y-a-s-kym-organza-detailed-dress/34162/2/39977358-c9fb-45f7-b6c9-d849e0da1853.jpg'],
                                       'price': '66,74',
                                       'sizes': ['36', '38', '40', '42'],
                                       'url': 'http://en.modagram.com//women/kym-organza-detailed-dress-black/detail/34162/150598'}}
